"""msg

Revision ID: 0f40f72ef10b
Revises: 1383d9c3eab6
Create Date: 2025-08-03 12:31:39.455380

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '0f40f72ef10b'
down_revision: Union[str, Sequence[str], None] = '1383d9c3eab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
