"""users_2

Revision ID: 1383d9c3eab6
Revises: 2d55aa5f21b8
Create Date: 2025-08-02 14:03:05.920235

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '1383d9c3eab6'
down_revision: Union[str, Sequence[str], None] = '2d55aa5f21b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
